version: "3.3"
services:
  tracking:
    build: ./
    networks:
      - backend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis
    networks:
      - backend
    ports:
      - 6379:6379
networks:
  backend: