version: "3.3"
services:
  tracking:
    build: ./
    command: /app/init.sh
    volumes:
      - ./src:/app/src
    networks:
      - backend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - backend
    ports:
      - 6379:6379
networks:
  backend: