version: "3.3"
services:
  tracking:
    build: ./
    command: npm run start:dev
    volumes:
      - ./:/app
    networks:
      - backend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
    ports:
      - 27017:27017
networks:
  backend:
volumes:
  mongodbdata: